FROM node:18.16.0

ARG ORIGIN
ARG DATABASE_URL
ARG ACCESS_TOKEN_SECRET
ARG REFRESH_TOKEN_SECRET
ARG REDIS_HOST
ARG REDIS_PORT
ARG REDIS_PASSWORD
ARG GOOGLE_ID
ARG GOOGLE_SECRET
ARG GOOGLE_CALLBACK
ARG KAKAO_ID
ARG KAKAO_CALLBACK
ARG AWS_BUCKET_REGION
ARG AWS_BUCKET_NAME
ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ARG DEFAULT_BADGE_LINK

ENV ORIGIN=$ORIGIN
ENV DATABASE_URL=$DATABASE_URL
ENV ACCESS_TOKEN_SECRET=$ACCESS_TOKEN_SECRET
ENV REFRESH_TOKEN_SECRET=$REFRESH_TOKEN_SECRET
ENV REDIS_HOST=$REDIS_HOST
ENV REDIS_PORT=$REDIS_PORT
ENV REDIS_PASSWORD=$REDIS_PASSWORD
ENV GOOGLE_ID=$GOOGLE_ID
ENV GOOGLE_SECRET=$GOOGLE_SECRET
ENV GOOGLE_CALLBACK=$GOOGLE_CALLBACK
ENV KAKAO_ID=$KAKAO_ID
ENV KAKAO_CALLBACK=$KAKAO_CALLBACK
ENV AWS_BUCKET_REGION=$AWS_BUCKET_REGION
ENV AWS_BUCKET_NAME=$AWS_BUCKET_NAME
ENV AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
ENV AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
ENV DEFAULT_BADGE_LINK=$DEFAULT_BADGE_LINK

WORKDIR /app
COPY package.json ./
COPY yarn.lock ./
RUN npm install -g pm2 

RUN yarn install --immutable --immutable-cache --check-cache

COPY . .

RUN yarn prisma generate

RUN yarn build

RUN yarn test

EXPOSE 3000

CMD ["pm2-runtime", "start", "dist/main.js"]
