export const initialBadgeTypes = [
  {
    id: 0,
    name: '기본 뱃지',
    description: '기본 뱃지',
    iconLink: '',
  },
  {
    id: 1,
    name: '일관성 뱃지1',
    description: '1주일 동안 작업 유지 시 획득',
    iconLink: '',
  },
  {
    id: 2,
    name: '일관성 뱃지2',
    description: '1개월 동안 작업 유지 시 획득',
    iconLink: '',
  },
  {
    id: 3,
    name: '일관성 뱃지3',
    description: '1년 동안 작업 유지 시 획득',
    iconLink: '',
  },
  {
    id: 4,
    name: '다양성 뱃지1',
    description: '매일 작업 100회 달성 시 획득',
    iconLink: '',
  },
  {
    id: 5,
    name: '다양성 뱃지2',
    description: '기한 작업 100회 달성 시 획득',
    iconLink: '',
  },
  {
    id: 6,
    name: '다양성 뱃지3',
    description: '무기한 작업 100회 달성 시 획득',
    iconLink: '',
  },
  {
    id: 7,
    name: '생산성 뱃지1',
    description: '하루 동안 작업 10회 달성 시 획득',
    iconLink: '',
  },
  {
    id: 8,
    name: '생산성 뱃지2',
    description: '1주일 동안 작업 100회 달성 시 획득',
    iconLink: '',
  },
  {
    id: 9,
    name: '생산성 뱃지3',
    description: '1개월 동안 작업 500회 달성 시 획득',
    iconLink: '',
  },
  {
    id: 10,
    name: '커스텀 뱃지1',
    description: '커스텀 뱃지1',
    iconLink: '',
  },
  {
    id: 11,
    name: '커스텀 뱃지2',
    description: '커스텀 뱃지2',
    iconLink: '',
  },
  {
    id: 12,
    name: '커스텀 뱃지3',
    description: '커스텀 뱃지3',
    iconLink: '',
  },
  {
    id: 13,
    name: '커스텀 뱃지4',
    description: '커스텀 뱃지4',
    iconLink: '',
  },
  {
    id: 14,
    name: '커스텀 뱃지5',
    description: '커스텀 뱃지5',
    iconLink: '',
  },
  {
    id: 15,
    name: '커스텀 뱃지6',
    description: '커스텀 뱃지6',
    iconLink: '',
  },
  {
    id: 16,
    name: '커스텀 뱃지7',
    description: '커스텀 뱃지7',
    iconLink: '',
  },
  {
    id: 17,
    name: '커스텀 뱃지8',
    description: '커스텀 뱃지8',
    iconLink: '',
  },
  {
    id: 18,
    name: '커스텀 뱃지9',
    description: '커스텀 뱃지9',
    iconLink: '',
  },
  {
    id: 19,
    name: '커스텀 뱃지10',
    description: '커스텀 뱃지10',
    iconLink: '',
  },
  {
    id: 20,
    name: '커스텀 뱃지11',
    description: '커스텀 뱃지11',
    iconLink: '',
  },
  {
    id: 21,
    name: '커스텀 뱃지12',
    description: '커스텀 뱃지12',
    iconLink: '',
  },
  {
    id: 22,
    name: '커스텀 뱃지13',
    description: '커스텀 뱃지13',
    iconLink: '',
  },
  {
    id: 23,
    name: '커스텀 뱃지14',
    description: '커스텀 뱃지14',
    iconLink: '',
  },
  {
    id: 24,
    name: '커스텀 뱃지15',
    description: '커스텀 뱃지15',
    iconLink: '',
  },
  {
    id: 25,
    name: '커스텀 뱃지16',
    description: '커스텀 뱃지16',
    iconLink: '',
  },
  {
    id: 26,
    name: '커스텀 뱃지17',
    description: '커스텀 뱃지17',
    iconLink: '',
  },
  {
    id: 27,
    name: '커스텀 뱃지18',
    description: '커스텀 뱃지18',
    iconLink: '',
  },
  {
    id: 28,
    name: '커스텀 뱃지19',
    description: '커스텀 뱃지19',
    iconLink: '',
  },
  {
    id: 29,
    name: '커스텀 뱃지20',
    description: '커스텀 뱃지20',
    iconLink: '',
  },

  {
    id: 30,
    name: '커스텀 뱃지21',
    description: '커스텀 뱃지21',
    iconLink: '',
  },
  {
    id: 31,
    name: '커스텀 뱃지22',
    description: '커스텀 뱃지22',
    iconLink: '',
  },
  {
    id: 32,
    name: '커스텀 뱃지23',
    description: '커스텀 뱃지23',
    iconLink: '',
  },
  {
    id: 33,
    name: '커스텀 뱃지24',
    description: '커스텀 뱃지24',
    iconLink: '',
  },
  {
    id: 34,
    name: '커스텀 뱃지25',
    description: '커스텀 뱃지25',
    iconLink: '',
  },
  {
    id: 35,
    name: '커스텀 뱃지26',
    description: '커스텀 뱃지26',
    iconLink: '',
  },
  {
    id: 36,
    name: '커스텀 뱃지27',
    description: '커스텀 뱃지27',
    iconLink: '',
  },
  {
    id: 37,
    name: '커스텀 뱃지28',
    description: '커스텀 뱃지28',
    iconLink: '',
  },
  {
    id: 38,
    name: '커스텀 뱃지29',
    description: '커스텀 뱃지29',
    iconLink: '',
  },
  {
    id: 39,
    name: '커스텀 뱃지30',
    description: '커스텀 뱃지30',
    iconLink: '',
  },
  {
    id: 40,
    name: '이달의 뱃지1',
    description: '2023년 7월 이달의 뱃지',
    iconLink: '',
  },
];
