export const BADGE_ID = '뱃지 고유 ID(INT)';
export const BADGE_LOG_ID = '뱃지 로그 고유 ID(INT)';
export const BADGE_NAME = '뱃지 이름';
export const BADGE_DESC = '뱃지 설명';
export const BADGE_ICON_LINK = '뱃지 아이콘 링크';
export const BADGE_TYPE = '뱃지 타입';
export const BADGE_PRICE = '뱃지 가격';
export const BADGE_PROGRESS = '뱃지 획득 진척도';

export const DEFAULT_BADGE_ID = 1;
export const CONSISTENCY_BADGE_ID1 = 2;
export const CONSISTENCY_BADGE_ID2 = 3;
export const CONSISTENCY_BADGE_ID3 = 4;
export const DIVERSITY_BADGE_ID1 = 5;
export const DIVERSITY_BADGE_ID2 = 6;
export const DIVERSITY_BADGE_ID3 = 7;
export const PRODUCTIVITY_BADGE_ID1 = 8;
export const PRODUCTIVITY_BADGE_ID2 = 9;
export const PRODUCTIVITY_BADGE_ID3 = 10;
