export const initialBadgeTypes = [
  {
    name: '기본 뱃지',
    description: '기본 뱃지',
    iconLink: '',
    type: 'SPECIAL',
  },
  {
    name: '일관성 뱃지1',
    description: '1주일 동안 작업 유지 시 획득',
    price: 1000,
    iconLink: '',
    type: 'ACHIEVEMENT',
  },
  {
    name: '일관성 뱃지2',
    description: '1개월 동안 작업 유지 시 획득',
    price: 5000,
    iconLink: '',
    type: 'ACHIEVEMENT',
  },
  {
    name: '일관성 뱃지3',
    description: '1년 동안 작업 유지 시 획득',
    price: 100000,
    iconLink: '',
    type: 'ACHIEVEMENT',
  },
  {
    name: '다양성 뱃지1',
    description: '매일 작업 100회 달성 시 획득',
    price: 5000,
    iconLink: '',
    type: 'ACHIEVEMENT',
  },
  {
    name: '다양성 뱃지2',
    description: '기한 작업 100회 달성 시 획득',
    price: 5000,
    iconLink: '',
    type: 'ACHIEVEMENT',
  },
  {
    name: '다양성 뱃지3',
    description: '무기한 작업 100회 달성 시 획득',
    price: 5000,
    iconLink: '',
    type: 'ACHIEVEMENT',
  },
  {
    name: '생산성 뱃지1',
    description: '하루 동안 작업 10회 달성 시 획득',
    price: 1000,
    iconLink: '',
    type: 'ACHIEVEMENT',
  },
  {
    name: '생산성 뱃지2',
    description: '1주일 동안 작업 100회 달성 시 획득',
    price: 2000,
    iconLink: '',
    type: 'ACHIEVEMENT',
  },
  {
    name: '생산성 뱃지3',
    description: '1개월 동안 작업 500회 달성 시 획득',
    price: 3000,
    iconLink: '',
    type: 'ACHIEVEMENT',
  },
  {
    name: '일반 뱃지1',
    description: '일반 뱃지1',
    price: 500,
    iconLink: '',
    type: 'NORMAL',
  },
  {
    name: '일반 뱃지2',
    description: '일반 뱃지2',
    price: 500,
    iconLink: '',
    type: 'NORMAL',
  },
  {
    name: '일반 뱃지3',
    description: '일반 뱃지3',
    price: 500,
    iconLink: '',
    type: 'NORMAL',
  },
  {
    name: '일반 뱃지4',
    description: '일반 뱃지4',
    price: 500,
    iconLink: '',
    type: 'NORMAL',
  },
  {
    name: '일반 뱃지5',
    description: '일반 뱃지5',
    price: 500,
    iconLink: '',
    type: 'NORMAL',
  },
  {
    name: '일반 뱃지6',
    description: '일반 뱃지6',
    price: 500,
    iconLink: '',
    type: 'NORMAL',
  },
  {
    name: '일반 뱃지7',
    description: '일반 뱃지7',
    price: 500,
    iconLink: '',
    type: 'NORMAL',
  },
  {
    name: '일반 뱃지8',
    description: '일반 뱃지8',
    price: 500,
    iconLink: '',
    type: 'NORMAL',
  },
  {
    name: '일반 뱃지9',
    description: '일반 뱃지9',
    price: 500,
    iconLink: '',
    type: 'NORMAL',
  },
  {
    name: '일반 뱃지10',
    description: '일반 뱃지10',
    price: 500,
    iconLink: '',
    type: 'NORMAL',
  },
  {
    name: '일반 뱃지11',
    description: '일반 뱃지11',
    price: 500,
    iconLink: '',
    type: 'NORMAL',
  },
  {
    name: '일반 뱃지12',
    description: '일반 뱃지12',
    price: 500,
    iconLink: '',
    type: 'NORMAL',
  },
  {
    name: '일반 뱃지13',
    description: '일반 뱃지13',
    price: 500,
    iconLink: '',
    type: 'NORMAL',
  },
  {
    name: '일반 뱃지14',
    description: '일반 뱃지14',
    price: 500,
    iconLink: '',
    type: 'NORMAL',
  },
  {
    name: '일반 뱃지15',
    description: '일반 뱃지15',
    price: 500,
    iconLink: '',
    type: 'NORMAL',
  },
  {
    name: '일반 뱃지16',
    description: '일반 뱃지16',
    price: 500,
    iconLink: '',
    type: 'NORMAL',
  },
  {
    name: '일반 뱃지17',
    description: '일반 뱃지17',
    price: 500,
    iconLink: '',
    type: 'NORMAL',
  },
  {
    name: '일반 뱃지18',
    description: '일반 뱃지18',
    price: 500,
    iconLink: '',
    type: 'NORMAL',
  },
  {
    name: '일반 뱃지19',
    description: '일반 뱃지19',
    price: 500,
    iconLink: '',
    type: 'NORMAL',
  },
  {
    name: '일반 뱃지20',
    description: '일반 뱃지20',
    price: 500,
    iconLink: '',
    type: 'NORMAL',
  },

  {
    name: '일반 뱃지21',
    description: '일반 뱃지21',
    price: 500,
    iconLink: '',
    type: 'NORMAL',
  },
  {
    name: '일반 뱃지22',
    description: '일반 뱃지22',
    price: 500,
    iconLink: '',
    type: 'NORMAL',
  },
  {
    name: '일반 뱃지23',
    description: '일반 뱃지23',
    price: 500,
    iconLink: '',
    type: 'NORMAL',
  },
  {
    name: '일반 뱃지24',
    description: '일반 뱃지24',
    price: 500,
    iconLink: '',
    type: 'NORMAL',
  },
  {
    name: '일반 뱃지25',
    description: '일반 뱃지25',
    price: 500,
    iconLink: '',
    type: 'NORMAL',
  },
  {
    name: '일반 뱃지26',
    description: '일반 뱃지26',
    price: 500,
    iconLink: '',
    type: 'NORMAL',
  },
  {
    name: '일반 뱃지27',
    description: '일반 뱃지27',
    price: 500,
    iconLink: '',
    type: 'NORMAL',
  },
  {
    name: '일반 뱃지28',
    description: '일반 뱃지28',
    price: 500,
    iconLink: '',
    type: 'NORMAL',
  },
  {
    name: '일반 뱃지29',
    description: '일반 뱃지29',
    price: 500,
    iconLink: '',
    type: 'NORMAL',
  },
  {
    name: '일반 뱃지30',
    description: '일반 뱃지30',
    price: 500,
    iconLink: '',
    type: 'NORMAL',
  },
  {
    name: '이달의 뱃지1',
    description: '2023년 8월 이달의 뱃지',
    iconLink: '',
    type: 'SPECIAL',
  },
];
