const AUTH_INVALID_TOKEN = '유효하지 않은 토큰입니다.';
const AUTH_EXPIRED_TOKEN = '만료된 토큰입니다';
const AUTH_EXPIRED_REFRESH_TOKEN = '만료된 리프레시 토큰입니다';

export { AUTH_INVALID_TOKEN, AUTH_EXPIRED_TOKEN, AUTH_EXPIRED_REFRESH_TOKEN };
