name: Run Tests on Pull Request

on:
  pull_request:
    branches:
      - main
      - dev
    types:
      - opened
      - synchronize

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      ORIGIN: ${{ secrets.ORIGIN }}
      DATABASE_URL: ${{ secrets.TEST_DB }}
      ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
      REFRESH_TOKEN_SECRET: ${{ secrets.REFRESH_TOKEN_SECRET }}
      REDIS_HOST: ${{ secrets.REDIS_HOST }}
      REDIS_PORT: ${{ secrets.REDIS_PORT }}
      REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
      GOOGLE_ID: ${{ secrets.GOOGLE_ID }}
      GOOGLE_SECRET: ${{ secrets.GOOGLE_SECRET }}
      GOOGLE_CALLBACK: ${{ secrets.GOOGLE_CALLBACK }}
      KAKAO_ID: ${{ secrets.KAKAO_ID }}
      KAKAO_CALLBACK: ${{ secrets.KAKAO_CALLBACK }}
      AWS_BUCKET_REGION: ${{ secrets.AWS_BUCKET_REGION }}
      AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      DEFAULT_BADGE_LINK: ${{ secrets.DEFAULT_BADGE_LINK }}
      SWAGGER_USER: ${{ secrets.SWAGGER_USER }}
      SWAGGER_PASSWORD: ${{ secrets.SWAGGER_PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.16.0'

      - name: Install dependencies
        run: yarn install --immutable --immutable-cache --check-cache

      - name: Run tests
        run: yarn test; yarn test:e2e
